name: Update

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Optional version input (e.g., 1-0-0 or leave empty for latest)'
        required: false
  repository_dispatch:
    types:
      - update_event

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set vars
        id: var
        run: |
          packageId="com.kiloo.subwaysurf"
          echo "packageId=$packageId" >> $GITHUB_OUTPUT
          if [ -z "${{ github.event.inputs.version }}" ]; then
            version=$(curl -s "https://gplayapi.herrerde.xyz/api/apps/$packageId" | jq -r '.version' | awk -F '.' '{print $1 "." $2 ".0"}')
          else
            version=$(echo "${{ github.event.inputs.version }}" | tr '.' '-')
          fi
          echo "version=$version" >> $GITHUB_OUTPUT
          changelog=$(curl -s "https://api.github.com/repos/HerrErde/subway-source/releases/latest" | jq -r '.body' | tr '\n' '\r\n')
          echo "changelog=$changelog" >> $GITHUB_OUTPUT

#      - name: Setup Python
#        uses: actions/setup-python@v5.1.0
#        with:
#          python-version: '3.x'
#          cache: 'pip'

      - name: Install
        run: pip install -r requirements.txt

      - name: Download Files
        run: python script/setup.py

      - name: Generate
        run: |
          python script/generate_characters.py
          python script/generate_boards.py
          python script/playerprofile.py
          python script/userstats.py
          python script/collection.py
          python script/challenges.py
          python script/calender.py
          python script/achievements.py
          python script/quests.py
          python script/chainoffers.py
          python script/ui_seen.py
          python script/citytours.py

      - name: increase version
        run: python script/update.py ${{steps.var.outputs.version}}

      - name: Generate List
        run: python script/list.py

      - name: Commit and push updated version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add src/
          git commit -am "auto update files ${{steps.var.outputs.version}}"
          git push

      - name: Convert & Zip
        run: |
          python script/convert.py
          python script/zip.py

      - name: Upload Data
        uses: softprops/action-gh-release@v2
        with:
          tag_name: '${{steps.var.outputs.version}}'
          body: '${{steps.var.outputs.changelog}}'
          files: |
            SubwayBooster.zip
            temp/data/characters_inventory.json
            temp/data/boards_inventory.json
            temp/data/generic_challenges.json

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
