name: Update

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update_event

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Download Files
        run: python script/setup.py

      - name: Generate
        run: |
          python script/generate_characters.py
          python script/generate_boards.py

      - name: Move Files
        run: |
          mv characters_inventory.json Android/data/com.kiloo.subwaysurf/files/profile/characters_inventory.json
          mv boards_inventory.json Android/data/com.kiloo.subwaysurf/files/profile/boards_inventory.json

      - name: Zip
        run: zip -r SubwayBooster.zip Android/

      - name: Increse version
        run: python script/update.py

      - name: Get version
        id: version
        run: echo version=$(jq -r '.version' Android/data/com.kiloo.subwaysurf/files/version.json) >> $GITHUB_OUTPUT

      - name: Commit and push updated version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "characters, boards"
          git push

        - name: Upload Data
          uses: softprops/action-gh-release@v1
          with:
            tag_name: '${{steps.version.outputs.version}}'
            files: SubwayBooster.zip

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
